### PR TITLE
Tpm exec shim

### PR DESCRIPTION
**Pull request by williamcroberts**

### CODE REVIEW

**Comment by williamcroberts** [comment]
Note that there is 2 approaches here:
1.  a simple C exec shim
2. A python command interpreter shell system

**Comment by liuqun** [comment]
The following tutorial is helpful if we are going to implement an interpreter using Python.
Source code for the series "Let's Build A Simple Interpreter"
- https://github.com/rspivak/lsbasi

**Comment by williamcroberts** [comment]
@liuqun Python has the command object which is perfect for what we're doing. This is actually functional, but not sure if tpm2_<foo> vs tpm2 foo is really worth it.

It might be better as an actual single executable comandlet like busybox.

**Comment by liuqun** [comment]
Example showing how to use the openssl command invoked with no sub-commands:
```
$ openssl
OpenSSL> list
openssl:Error: 'list' is an invalid command.

Standard commands
asn1parse         ca                ciphers           cms               
crl               crl2pkcs7         dgst              dh                
dhparam           dsa               dsaparam          ec                
ecparam           enc               engine            errstr            
gendh             gendsa            genpkey           genrsa            
nseq              ocsp              passwd            pkcs12            
pkcs7             pkcs8             pkey              pkeyparam         
pkeyutl           prime             rand              req               
rsa               rsautl            s_client          s_server          
s_time            sess_id           smime             speed             
spkac             srp               ts                verify            
version           x509              

Message Digest commands (see the `dgst' command for more details)
md4               md5               rmd160            sha               
sha1              

Cipher commands (see the `enc' command for more details)
aes-128-cbc       aes-128-ecb       aes-192-cbc       aes-192-ecb       
aes-256-cbc       aes-256-ecb       base64            bf                
bf-cbc            bf-cfb            bf-ecb            bf-ofb            
camellia-128-cbc  camellia-128-ecb  camellia-192-cbc  camellia-192-ecb  
camellia-256-cbc  camellia-256-ecb  cast              cast-cbc          
cast5-cbc         cast5-cfb         cast5-ecb         cast5-ofb         
des               des-cbc           des-cfb           des-ecb           
des-ede           des-ede-cbc       des-ede-cfb       des-ede-ofb       
des-ede3          des-ede3-cbc      des-ede3-cfb      des-ede3-ofb      
des-ofb           des3              desx              rc2               
rc2-40-cbc        rc2-64-cbc        rc2-cbc           rc2-cfb           
rc2-ecb           rc2-ofb           rc4               rc4-40            
seed              seed-cbc          seed-cfb          seed-ecb          
seed-ofb          

OpenSSL> sha1
abc<Ctrl-D><Ctrl-D>
(stdin)= a9993e364706816aba3e25717850c26c9cd0d89d
OpenSSL> 
```

**Comment by liuqun** [comment]
Related to issue https://github.com/01org/tpm2-tools/issues/589

If we use a command line front end ("tpm2") to invoke sub-commands and with the bash-completion support for our tpm2_xxx commands, it will be more friendly to other developers.

- `sudo apt-get install bash-completion`
- `tail ~/.bashrc`
```
if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi
```

Check openssl tools that have already been supported by bash-completion
- `dpkg-query --listfiles bash-completion | grep openssl`
/usr/share/bash-completion/completions/openssl

**Comment by williamcroberts** [comment]
@liuqun you can modify the Python command object to get help output. Rather than doing the default handler hack I did, one could even add each command into the class properly. So it looks like the direction you'd rather go is the Python version shell.

**Comment by williamcroberts** [comment]
@liuqun bash completion support in general would be nice.

**Pull request closed without merging**
