### PR TITLE
README.md: Update URLs to account for tpm2.0-tools -> tpm2-tools rename.

### PR DESCRIPTION
**Pull request by flihp**
Signed-off-by: Philip Tricca <flihp@twobit.us>

### CODE REVIEW

**Comment by martinezjavier** [comment]
BTW, I also like tpm2-tools more but I think that all the occurrences of the old project name should be replaced in the code base:

$ git grep tpm2.0-tools | wc -l
63

**Comment by martinezjavier** [comment]
BTW, I also like tpm2-tools more but I think that all the occurrences of the old project name should be replaced in the code base:

$ git grep tpm2.0-tools | wc -l
63

**Comment by martinezjavier** [comment]
@williamcroberts great.

**Comment by williamcroberts** [comment]
On #394

**Pull request closed without merging**
