### PR TITLE
option fixing: move to single getopt

### PR DESCRIPTION
**Pull request by williamcroberts**
Parsing with multiple invocations of getopt
and strpping known options before invoking the
tool has resulted in some bugs. getopt is set
up to have all known options set up before the
call. A side affect of the old design was that
tool options could end up in a weird state.

For instance -I- for tpm2_create would not be parsed
correctly and an extra optarg would be added to
argv.

Redesign the option handling to use a single getopt
call, and develop new entry points for the tools.

New Entry Points:
1. tpm2_tool_onstart - The initial entry point to get
   the option arguments for getopt. This entry point
   also sets callbacks for:
    - option handling
    - argument handling

2. tpm2_tool_onrun - The tool executes the requested
   functionality.

3. tpm2_tool_exit - this is guarenteed to be called
   before exiting while the tcti context is still
   valid. This can be used for any cleanup done in a
   previous stage.

Major Contributors:
 - Javier Martinez Canillas <javierm@redhat.com>

Signed-off-by: William Roberts <william.c.roberts@intel.com>

### CODE REVIEW

**Comment by williamcroberts** [comment]
@martinezjavier - Here is the pr off of tpm2-option-revamp after squashing and cleaning up. I know you have some more changes you want to add to this, so I won't pull this. But I wanted to see if it would pass the CI runs on Travis.

**Comment by martinezjavier** [comment]
@williamcroberts Ok, perfect. I'll send a PR against this new rebased branch then.  So you can squash the fixes and push to update the PR.

**Comment by williamcroberts** [comment]
SGTM

**Comment by williamcroberts** [comment]
@martinezjavier code coverage increased! Also, we don't need to NULL terminate our tool option arrays, we can delete those lines, as the calloc has takes care of it.

**Comment by martinezjavier** [comment]
@williamcroberts cool about the code coverage increase! Ok, feel free to do any additional fixups before pushing.

**Comment by williamcroberts** [comment]
@martinezjavier Do you want me to wait on those changes from you?

**Comment by martinezjavier** [comment]
@williamcroberts I won't have more time to work on this today, sorry. But I can remove the sentinel entry in the tables tomorrow if you want.

**Comment by williamcroberts** [comment]
@martinezjavier that's fine, Im going to close this PR and disable building on the tpm2-options-revamp branch and push the delete of the NULL in arrays, and then you can submit a PR to it. Monday ill pull over what we have to master.

**Comment by martinezjavier** [comment]
@williamcroberts Ok, wouldn't make more sense to first squash the fixups in PR #470 before deleting the NULL sentinel in the tables or did I misunderstood what you said?

I don't have more fixes queued than the ones I included in that PR.

**Pull request closed without merging**
